<?php

namespace Database\Seeders;

use App\Models\Badge;
use Illuminate\Database\Seeder;

class BadgeSeeder extends Seeder
{
    public function run(): void
    {
        $badges = [
            // ── Trader Tier (by total completed trade count) ──────────────────
            [
                'slug'           => 'shrimp',
                'name'           => 'Shrimp',
                'emoji'          => '🦐',
                'description'    => 'Completed your first trade. Every whale started here.',
                'category'       => 'trader_tier',
                'criteria_type'  => 'trade_count',
                'criteria_value' => 1,
                'color'          => '#7dd3fc',
                'rarity'         => 'common',
                'is_special'     => false,
                'sort_order'     => 10,
            ],
            [
                'slug'           => 'crab',
                'name'           => 'Crab',
                'emoji'          => '🦀',
                'description'    => 'Completed 5 trades. Scuttling up the ranks.',
                'category'       => 'trader_tier',
                'criteria_type'  => 'trade_count',
                'criteria_value' => 5,
                'color'          => '#fb923c',
                'rarity'         => 'common',
                'is_special'     => false,
                'sort_order'     => 20,
            ],
            [
                'slug'           => 'octopus',
                'name'           => 'Octopus',
                'emoji'          => '🐙',
                'description'    => 'Completed 15 trades. Juggling multiple positions like a pro.',
                'category'       => 'trader_tier',
                'criteria_type'  => 'trade_count',
                'criteria_value' => 15,
                'color'          => '#c084fc',
                'rarity'         => 'common',
                'is_special'     => false,
                'sort_order'     => 30,
            ],
            [
                'slug'           => 'fish',
                'name'           => 'Fish',
                'emoji'          => '🐟',
                'description'    => 'Completed 30 trades. Swimming confidently in crypto waters.',
                'category'       => 'trader_tier',
                'criteria_type'  => 'trade_count',
                'criteria_value' => 30,
                'color'          => '#34d399',
                'rarity'         => 'rare',
                'is_special'     => false,
                'sort_order'     => 40,
            ],
            [
                'slug'           => 'dolphin',
                'name'           => 'Dolphin',
                'emoji'          => '🐬',
                'description'    => 'Completed 75 trades. Riding the waves with experience.',
                'category'       => 'trader_tier',
                'criteria_type'  => 'trade_count',
                'criteria_value' => 75,
                'color'          => '#22d3ee',
                'rarity'         => 'rare',
                'is_special'     => false,
                'sort_order'     => 50,
            ],
            [
                'slug'           => 'shark',
                'name'           => 'Shark',
                'emoji'          => '🦈',
                'description'    => 'Completed 150 trades. A powerful force in the market.',
                'category'       => 'trader_tier',
                'criteria_type'  => 'trade_count',
                'criteria_value' => 150,
                'color'          => '#f472b6',
                'rarity'         => 'rare',
                'is_special'     => false,
                'sort_order'     => 60,
            ],
            [
                'slug'           => 'whale',
                'name'           => 'Whale',
                'emoji'          => '🐋',
                'description'    => 'Completed 300 trades. You move markets. Legendary status.',
                'category'       => 'trader_tier',
                'criteria_type'  => 'trade_count',
                'criteria_value' => 300,
                'color'          => '#fbbf24',
                'rarity'         => 'legendary',
                'is_special'     => false,
                'sort_order'     => 70,
            ],

            // ── Volume Tier (by total NGN traded) ─────────────────────────────
            [
                'slug'           => 'miner',
                'name'           => 'Miner',
                'emoji'          => '⛏️',
                'description'    => 'Traded over ₦1,000,000 in total volume. Digging for gains.',
                'category'       => 'volume_tier',
                'criteria_type'  => 'trade_volume_ngn',
                'criteria_value' => 1000000,
                'color'          => '#a3e635',
                'rarity'         => 'rare',
                'is_special'     => false,
                'sort_order'     => 80,
            ],
            [
                'slug'           => 'diamond',
                'name'           => 'Diamond',
                'emoji'          => '💎',
                'description'    => 'Traded over ₦5,000,000 in total volume. Crystalline conviction.',
                'category'       => 'volume_tier',
                'criteria_type'  => 'trade_volume_ngn',
                'criteria_value' => 5000000,
                'color'          => '#67e8f9',
                'rarity'         => 'legendary',
                'is_special'     => false,
                'sort_order'     => 90,
            ],

            // ── Account Badges (auto) ─────────────────────────────────────────
            [
                'slug'           => 'genesis-block',
                'name'           => 'Genesis Block',
                'emoji'          => '🌱',
                'description'    => 'Created your KayXchange account. Welcome to the chain.',
                'category'       => 'account',
                'criteria_type'  => 'genesis',
                'criteria_value' => 0,
                'color'          => '#00cc00',
                'rarity'         => 'common',
                'is_special'     => false,
                'sort_order'     => 1,
            ],
            [
                'slug'           => 'vault-keeper',
                'name'           => 'Vault Keeper',
                'emoji'          => '🔐',
                'description'    => 'Set your security PIN. Your vault is locked.',
                'category'       => 'account',
                'criteria_type'  => 'pin_set',
                'criteria_value' => 0,
                'color'          => '#a78bfa',
                'rarity'         => 'common',
                'is_special'     => false,
                'sort_order'     => 2,
            ],
            [
                'slug'           => 'banked',
                'name'           => 'Banked',
                'emoji'          => '🏦',
                'description'    => 'Added a bank account. Ready to receive NGN payouts.',
                'category'       => 'account',
                'criteria_type'  => 'bank_added',
                'criteria_value' => 0,
                'color'          => '#60a5fa',
                'rarity'         => 'common',
                'is_special'     => false,
                'sort_order'     => 3,
            ],
            [
                'slug'           => 'verified',
                'name'           => 'Verified',
                'emoji'          => '✅',
                'description'    => 'KYC identity verified. You\'re officially authenticated on-chain.',
                'category'       => 'account',
                'criteria_type'  => 'kyc_verified',
                'criteria_value' => 0,
                'color'          => '#00cc00',
                'rarity'         => 'rare',
                'is_special'     => false,
                'sort_order'     => 4,
            ],

            // ── Special (admin-awarded only) ──────────────────────────────────
            [
                'slug'           => 'og-holder',
                'name'           => 'OG Holder',
                'emoji'          => '👑',
                'description'    => 'An original early adopter of KayXchange. Respect.',
                'category'       => 'special',
                'criteria_type'  => 'admin_awarded',
                'criteria_value' => 0,
                'color'          => '#fbbf24',
                'rarity'         => 'legendary',
                'is_special'     => true,
                'sort_order'     => 100,
            ],
            [
                'slug'           => 'hodler',
                'name'           => 'HODLer',
                'emoji'          => '🔥',
                'description'    => 'Demonstrated unwavering commitment to the platform.',
                'category'       => 'special',
                'criteria_type'  => 'admin_awarded',
                'criteria_value' => 0,
                'color'          => '#ef4444',
                'rarity'         => 'legendary',
                'is_special'     => true,
                'sort_order'     => 101,
            ],
            [
                'slug'           => 'lightning-trader',
                'name'           => 'Lightning Trader',
                'emoji'          => '⚡',
                'description'    => 'Recognised for exceptional speed and frequency of trades.',
                'category'       => 'special',
                'criteria_type'  => 'admin_awarded',
                'criteria_value' => 0,
                'color'          => '#f59e0b',
                'rarity'         => 'rare',
                'is_special'     => true,
                'sort_order'     => 102,
            ],
            [
                'slug'           => 'diamond-hands',
                'name'           => 'Diamond Hands',
                'emoji'          => '💠',
                'description'    => 'A trusted pillar of the KayXchange community.',
                'category'       => 'special',
                'criteria_type'  => 'admin_awarded',
                'criteria_value' => 0,
                'color'          => '#67e8f9',
                'rarity'         => 'legendary',
                'is_special'     => true,
                'sort_order'     => 103,
            ],
        ];

        foreach ($badges as $data) {
            Badge::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
